import { Chapter, QuizQuestion } from './types'

// ─── Chapters ─────────────────────────────────────────────────────────────────

export const CHAPTERS: Chapter[] = [
  { id: 1, title: 'Comprendre sa voiture', emoji: '🚗', description: 'Les pièces, commandes et instruments de bord', quiz_count: 15, is_free: true },
  { id: 2, title: 'Actions de base', emoji: '🔑', description: 'Démarrer, s\'arrêter, diriger et changer de vitesse', quiz_count: 15, is_free: true },
  { id: 3, title: 'La signalisation routière', emoji: '🚦', description: 'Panneaux de danger, interdiction et obligation', quiz_count: 15, is_free: true },
  { id: 4, title: 'Les règles de priorité', emoji: '⚖️', description: 'Intersections, ronds-points et cédez-le-passage', quiz_count: 15, is_free: false },
  { id: 5, title: 'Conduite en ville', emoji: '🏙️', description: 'Vitesses, piétons et circulation urbaine', quiz_count: 15, is_free: false },
  { id: 6, title: 'Stationnement & manœuvres', emoji: '🅿️', description: 'Se garer, faire demi-tour et reculer', quiz_count: 15, is_free: false },
  { id: 7, title: 'Gestion des risques', emoji: '⚠️', description: 'Distances de sécurité, dépassement et vigilance', quiz_count: 15, is_free: false },
  { id: 8, title: 'Situations d\'urgence', emoji: '🚨', description: 'Pannes, accidents et procédures d\'urgence', quiz_count: 15, is_free: false },
  { id: 9, title: 'Examen Blanc Final', emoji: '📋', description: 'Simulation complète — 40 questions, 30 minutes', quiz_count: 40, is_free: false },
]

// ─── Chapter 1 — Comprendre sa voiture ───────────────────────────────────────

const ch1: QuizQuestion[] = [
  {
    id: 'ch1_q1',
    chapter_id: 1,
    type: 'image_selection',
    question: 'Lesquels de ces objets se trouvent dans une voiture ?',
    options: [
      { id: 'steering_wheel', text: 'Volant', image_key: 'steering_wheel' },
      { id: 'laptop', text: 'Ordinateur', image_key: 'laptop' },
      { id: 'brake_pedal', text: 'Pédale', image_key: 'brake_pedal' },
      { id: 'bicycle', text: 'Guidon', image_key: 'bicycle' },
      { id: 'mirror', text: 'Rétroviseur', image_key: 'rearview_mirror' },
      { id: 'phone', text: 'Téléphone', image_key: 'phone' },
    ],
    correct_ids: ['steering_wheel', 'brake_pedal', 'mirror'],
    explanation: 'Le volant, les pédales et le rétroviseur sont des éléments de base d\'une voiture.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q2',
    chapter_id: 1,
    type: 'scenario',
    question: 'Lequel de ces éléments permet de diriger la voiture ?',
    options: [
      { id: 'a', label: 'A', text: 'Le volant' },
      { id: 'b', label: 'B', text: 'Le levier de vitesses' },
      { id: 'c', label: 'C', text: 'Le frein à main' },
      { id: 'd', label: 'D', text: 'Le tableau de bord' },
    ],
    correct_ids: ['a'],
    explanation: 'Le volant permet de diriger la voiture à gauche ou à droite.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q3',
    chapter_id: 1,
    type: 'scenario',
    question: 'Lequel est l\'embrayage ?',
    options: [
      { id: 'a', label: 'A', text: 'La pédale à gauche' },
      { id: 'b', label: 'B', text: 'La pédale au centre' },
      { id: 'c', label: 'C', text: 'La pédale à droite' },
      { id: 'd', label: 'D', text: 'La pédale en haut' },
    ],
    correct_ids: ['a'],
    explanation: 'L\'embrayage est toujours la pédale la plus à gauche. Il permet de changer les vitesses.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q4',
    chapter_id: 1,
    type: 'scenario',
    question: 'Lequel est le frein ?',
    options: [
      { id: 'a', label: 'A', text: 'La pédale à gauche' },
      { id: 'b', label: 'B', text: 'La pédale au centre' },
      { id: 'c', label: 'C', text: 'La pédale à droite' },
      { id: 'd', label: 'D', text: 'Le frein à main' },
    ],
    correct_ids: ['b'],
    explanation: 'Le frein est la pédale du milieu. Il permet de ralentir et d\'arrêter le véhicule.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q5',
    chapter_id: 1,
    type: 'scenario',
    question: 'Quelle pédale contrôle la vitesse du moteur ?',
    options: [
      { id: 'a', label: 'A', text: 'L\'embrayage (gauche)' },
      { id: 'b', label: 'B', text: 'Le frein (centre)' },
      { id: 'c', label: 'C', text: 'L\'accélérateur (droite)' },
      { id: 'd', label: 'D', text: 'Le frein à main' },
    ],
    correct_ids: ['c'],
    explanation: 'L\'accélérateur est la pédale la plus à droite. Appuyer dessus augmente la vitesse.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q6',
    chapter_id: 1,
    type: 'step_ordering',
    question: 'Quel est l\'ordre correct des pédales de gauche à droite ?',
    options: [
      { id: 'step_acc', text: 'Accélérateur' },
      { id: 'step_clutch', text: 'Embrayage' },
      { id: 'step_brake', text: 'Frein' },
    ],
    correct_ids: ['step_clutch', 'step_brake', 'step_acc'],
    explanation: 'De gauche à droite : Embrayage — Frein — Accélérateur. Toujours dans cet ordre.',
    difficulty: 'medium',
  },
  {
    id: 'ch1_q7',
    chapter_id: 1,
    type: 'true_false',
    question: 'L\'embrayage doit être enfoncé pour démarrer le moteur sur une voiture manuelle.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Sur les voitures manuelles modernes, enfoncer l\'embrayage est nécessaire pour démarrer (mesure de sécurité).',
    difficulty: 'medium',
  },
  {
    id: 'ch1_q8',
    chapter_id: 1,
    type: 'scenario',
    question: 'Pour changer de vitesse, quelle pédale doit être enfoncée en premier ?',
    options: [
      { id: 'a', label: 'A', text: 'L\'embrayage' },
      { id: 'b', label: 'B', text: 'Le frein' },
      { id: 'c', label: 'C', text: 'L\'accélérateur' },
      { id: 'd', label: 'D', text: 'Aucune pédale' },
    ],
    correct_ids: ['a'],
    explanation: 'Toujours enfoncer l\'embrayage avant de changer de rapport de vitesse.',
    difficulty: 'medium',
  },
  {
    id: 'ch1_q9',
    chapter_id: 1,
    type: 'sign_recognition',
    question: 'Que signifie ce voyant lumineux sur le tableau de bord ?',
    image_key: 'warning_engine',
    options: [
      { id: 'a', label: 'A', text: 'Problème moteur — arrêtez-vous' },
      { id: 'b', label: 'B', text: 'Pression des pneus faible' },
      { id: 'c', label: 'C', text: 'Réservoir vide' },
      { id: 'd', label: 'D', text: 'Ceinture non bouclée' },
    ],
    correct_ids: ['a'],
    explanation: 'Le voyant moteur indique un problème mécanique. Arrêtez-vous dès que possible.',
    difficulty: 'medium',
  },
  {
    id: 'ch1_q10',
    chapter_id: 1,
    type: 'sign_recognition',
    question: 'Que signifie ce voyant ?',
    image_key: 'warning_oil',
    options: [
      { id: 'a', label: 'A', text: 'Niveau d\'huile faible — coupez le moteur' },
      { id: 'b', label: 'B', text: 'Température moteur élevée' },
      { id: 'c', label: 'C', text: 'Frein à main serré' },
      { id: 'd', label: 'D', text: 'Batterie faible' },
    ],
    correct_ids: ['a'],
    explanation: 'Un voyant de pression d\'huile allumé signifie que vous devez couper le moteur immédiatement.',
    difficulty: 'medium',
  },
  {
    id: 'ch1_q11',
    chapter_id: 1,
    type: 'image_selection',
    question: 'Sélectionnez tous les équipements de sécurité obligatoires',
    options: [
      { id: 'seatbelt', text: 'Ceinture de sécurité', image_key: 'seatbelt' },
      { id: 'triangle', text: 'Triangle de signalisation', image_key: 'warning_triangle' },
      { id: 'fire_ext', text: 'Extincteur', image_key: 'fire_extinguisher' },
      { id: 'vest', text: 'Gilet réfléchissant', image_key: 'reflective_vest' },
      { id: 'kit', text: 'Trousse de secours', image_key: 'first_aid_kit' },
      { id: 'spare', text: 'Roue de secours', image_key: 'spare_wheel' },
    ],
    correct_ids: ['seatbelt', 'triangle', 'vest'],
    explanation: 'Au Togo, la ceinture, le triangle de signalisation et le gilet réfléchissant sont obligatoires.',
    difficulty: 'medium',
  },
  {
    id: 'ch1_q12',
    chapter_id: 1,
    type: 'true_false',
    question: 'Les enfants de moins de 10 ans doivent obligatoirement s\'asseoir à l\'arrière.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Les enfants de moins de 10 ans doivent être installés à l\'arrière du véhicule pour leur sécurité.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q13',
    chapter_id: 1,
    type: 'scenario',
    question: 'Votre voiture tombe en panne sur la route. Que placez-vous derrière elle ?',
    options: [
      { id: 'a', label: 'A', text: 'Le triangle de signalisation' },
      { id: 'b', label: 'B', text: 'Le gilet réfléchissant' },
      { id: 'c', label: 'C', text: 'La roue de secours' },
      { id: 'd', label: 'D', text: 'L\'extincteur' },
    ],
    correct_ids: ['a'],
    explanation: 'Le triangle de signalisation doit être placé derrière le véhicule pour avertir les autres conducteurs.',
    difficulty: 'easy',
  },
  {
    id: 'ch1_q14',
    chapter_id: 1,
    type: 'scenario',
    question: 'Quelle pédale ne doit jamais rester enfoncée en conduisant ?',
    options: [
      { id: 'a', label: 'A', text: 'L\'embrayage' },
      { id: 'b', label: 'B', text: 'Le frein' },
      { id: 'c', label: 'C', text: 'L\'accélérateur' },
      { id: 'd', label: 'D', text: 'Toutes les pédales' },
    ],
    correct_ids: ['a'],
    explanation: 'Garder l\'embrayage enfoncé en roulant use l\'embrayage et est dangereux. C\'est "conduire en patinant".',
    difficulty: 'hard',
  },
  {
    id: 'ch1_q15',
    chapter_id: 1,
    type: 'step_ordering',
    question: 'Comment arrêter votre voiture en toute sécurité sur le bord de la route ?',
    options: [
      { id: 's1', text: 'Activez les feux de détresse' },
      { id: 's2', text: 'Serrez le frein à main' },
      { id: 's3', text: 'Ralentissez progressivement' },
      { id: 's4', text: 'Garez-vous sur le côté droit' },
      { id: 's5', text: 'Coupez le moteur' },
    ],
    correct_ids: ['s1', 's3', 's4', 's5', 's2'],
    explanation: 'Il faut d\'abord signaler, ralentir, puis se garer avant de couper le moteur et serrer le frein.',
    difficulty: 'hard',
  },
]

// ─── Chapter 2 — Actions de base ─────────────────────────────────────────────

const ch2: QuizQuestion[] = [
  {
    id: 'ch2_q1',
    chapter_id: 2,
    type: 'step_ordering',
    question: 'Ordonnez les étapes pour démarrer correctement une voiture manuelle',
    options: [
      { id: 's1', text: 'Bouclez la ceinture' },
      { id: 's2', text: 'Vérifiez les rétroviseurs' },
      { id: 's3', text: 'Mettez le contact' },
      { id: 's4', text: 'Appuyez sur l\'embrayage' },
      { id: 's5', text: 'Passez la première vitesse' },
      { id: 's6', text: 'Relâchez le frein à main' },
      { id: 's7', text: 'Relâchez l\'embrayage doucement' },
    ],
    correct_ids: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
    explanation: 'L\'ordre de démarrage garantit la sécurité et protège la mécanique du véhicule.',
    difficulty: 'medium',
  },
  {
    id: 'ch2_q2',
    chapter_id: 2,
    type: 'true_false',
    question: 'On peut démarrer une voiture manuelle sans enfoncer l\'embrayage.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Il faut obligatoirement enfoncer l\'embrayage pour démarrer une voiture manuelle moderne.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q3',
    chapter_id: 2,
    type: 'true_false',
    question: 'On doit toujours démarrer le moteur avec le levier de vitesses en position neutre.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Démarrer en position neutre évite que le véhicule ne bondisse en avant.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q4',
    chapter_id: 2,
    type: 'scenario',
    question: 'Le moteur cale à un carrefour. Que faites-vous en premier ?',
    options: [
      { id: 'a', label: 'A', text: 'Activer les feux de détresse' },
      { id: 'b', label: 'B', text: 'Ouvrir le capot' },
      { id: 'c', label: 'C', text: 'Appuyer sur l\'accélérateur à fond' },
      { id: 'd', label: 'D', text: 'Sortir du véhicule' },
    ],
    correct_ids: ['a'],
    explanation: 'En cas de panne, activez d\'abord les feux de détresse pour signaler votre présence.',
    difficulty: 'medium',
  },
  {
    id: 'ch2_q5',
    chapter_id: 2,
    type: 'scenario',
    question: 'Vous voulez ralentir rapidement. Quelle pédale utilisez-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'L\'embrayage' },
      { id: 'b', label: 'B', text: 'Le frein' },
      { id: 'c', label: 'C', text: 'L\'accélérateur' },
      { id: 'd', label: 'D', text: 'Les deux pieds' },
    ],
    correct_ids: ['b'],
    explanation: 'Pour ralentir, appuyez sur le frein. En urgence, vous pouvez aussi enfoncer l\'embrayage simultanément.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q6',
    chapter_id: 2,
    type: 'scenario',
    question: 'Votre voiture recule légèrement au démarrage en côte. Que corrigez-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Relâchez le frein à main plus lentement' },
      { id: 'b', label: 'B', text: 'Appuyez plus fort sur l\'accélérateur' },
      { id: 'c', label: 'C', text: 'Coordonnez l\'embrayage et l\'accélérateur avant de lâcher le frein à main' },
      { id: 'd', label: 'D', text: 'Passez en marche arrière' },
    ],
    correct_ids: ['c'],
    explanation: 'La coordination embrayage-accélérateur-frein à main est la clé du démarrage en côte.',
    difficulty: 'hard',
  },
  {
    id: 'ch2_q7',
    chapter_id: 2,
    type: 'scenario',
    question: 'À quelle vitesse maximale êtes-vous autorisé à rouler en agglomération ?',
    options: [
      { id: 'a', label: 'A', text: '30 km/h' },
      { id: 'b', label: 'B', text: '50 km/h' },
      { id: 'c', label: 'C', text: '70 km/h' },
      { id: 'd', label: 'D', text: '90 km/h' },
    ],
    correct_ids: ['b'],
    explanation: 'La vitesse maximale en agglomération est de 50 km/h, sauf signalisation contraire.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q8',
    chapter_id: 2,
    type: 'true_false',
    question: 'Il est obligatoire d\'utiliser le clignotant avant de tourner.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Le clignotant doit être activé avant tout changement de direction pour avertir les autres usagers.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q9',
    chapter_id: 2,
    type: 'scenario',
    question: 'Vous avez oublié de desserrer le frein à main. Qu\'observez-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'La voiture ne démarre pas' },
      { id: 'b', label: 'B', text: 'La voiture ne roule pas librement et sent le brûlé' },
      { id: 'c', label: 'C', text: 'Le moteur s\'arrête automatiquement' },
      { id: 'd', label: 'D', text: 'Les phares s\'allument' },
    ],
    correct_ids: ['b'],
    explanation: 'Rouler avec le frein à main serré cause une résistance et peut endommager les freins.',
    difficulty: 'medium',
  },
  {
    id: 'ch2_q10',
    chapter_id: 2,
    type: 'scenario',
    question: 'Quelle est la distance de sécurité recommandée entre deux véhicules sur route ?',
    options: [
      { id: 'a', label: 'A', text: '1 seconde de distance' },
      { id: 'b', label: 'B', text: '2 secondes de distance' },
      { id: 'c', label: 'C', text: '5 mètres fixes' },
      { id: 'd', label: 'D', text: '10 mètres fixes' },
    ],
    correct_ids: ['b'],
    explanation: 'La règle des 2 secondes : choisissez un repère fixe et vérifiez que 2 secondes s\'écoulent entre vous et le véhicule devant.',
    difficulty: 'medium',
  },
  {
    id: 'ch2_q11',
    chapter_id: 2,
    type: 'true_false',
    question: 'L\'utilisation du téléphone au volant est autorisée si vous parlez brièvement.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'L\'utilisation du téléphone en conduisant est interdite, même brièvement. Arrêtez-vous pour téléphoner.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q12',
    chapter_id: 2,
    type: 'scenario',
    question: 'Quelle est la première chose à faire en cas d\'accident de la route ?',
    options: [
      { id: 'a', label: 'A', text: 'Appeler votre assurance' },
      { id: 'b', label: 'B', text: 'Sécuriser les lieux (triangle + gilet) puis appeler les secours' },
      { id: 'c', label: 'C', text: 'Partir avant l\'arrivée de la police' },
      { id: 'd', label: 'D', text: 'Prendre des photos uniquement' },
    ],
    correct_ids: ['b'],
    explanation: 'En cas d\'accident : sécurisez les lieux, portez votre gilet, posez le triangle, puis appelez les secours.',
    difficulty: 'medium',
  },
  {
    id: 'ch2_q13',
    chapter_id: 2,
    type: 'scenario',
    question: 'À combien de mètres les feux de route éblouissent-ils les autres conducteurs ?',
    options: [
      { id: 'a', label: 'A', text: '50 m' },
      { id: 'b', label: 'B', text: '100 m' },
      { id: 'c', label: 'C', text: '150 m' },
      { id: 'd', label: 'D', text: '200 m' },
    ],
    correct_ids: ['c'],
    explanation: 'Les feux de route doivent être éteints dès que vous croisez un véhicule à moins de 150 m.',
    difficulty: 'hard',
  },
  {
    id: 'ch2_q14',
    chapter_id: 2,
    type: 'true_false',
    question: 'Il est autorisé de faire un demi-tour sur une autoroute.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Les demi-tours sont strictement interdits sur autoroute. Ils sont extrêmement dangereux.',
    difficulty: 'easy',
  },
  {
    id: 'ch2_q15',
    chapter_id: 2,
    type: 'step_ordering',
    question: 'Ordonnez les étapes pour changer de voie en toute sécurité',
    options: [
      { id: 's1', text: 'Regarder dans le rétroviseur' },
      { id: 's2', text: 'Mettre le clignotant' },
      { id: 's3', text: 'Vérifier l\'angle mort' },
      { id: 's4', text: 'Effectuer la manœuvre progressivement' },
      { id: 's5', text: 'Désactiver le clignotant' },
    ],
    correct_ids: ['s1', 's2', 's3', 's4', 's5'],
    explanation: 'Vérification rétroviseur → clignotant → angle mort → déplacement progressif.',
    difficulty: 'medium',
  },
]

// ─── Chapter 3 — La signalisation routière ────────────────────────────────────

const ch3: QuizQuestion[] = [
  {
    id: 'ch3_q1',
    chapter_id: 3,
    type: 'sign_recognition',
    question: 'Que signifie ce panneau ?',
    image_key: 'sign_stop',
    options: [
      { id: 'a', label: 'A', text: 'Ralentir' },
      { id: 'b', label: 'B', text: 'Arrêt obligatoire' },
      { id: 'c', label: 'C', text: 'Cédez le passage' },
      { id: 'd', label: 'D', text: 'Sens interdit' },
    ],
    correct_ids: ['b'],
    explanation: 'Le panneau STOP (octogone rouge) impose un arrêt complet, même si la voie est libre.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q2',
    chapter_id: 3,
    type: 'sign_recognition',
    question: 'Que signifie ce panneau ?',
    image_key: 'sign_give_way',
    options: [
      { id: 'a', label: 'A', text: 'Voie prioritaire' },
      { id: 'b', label: 'B', text: 'Cédez le passage' },
      { id: 'c', label: 'C', text: 'Arrêt obligatoire' },
      { id: 'd', label: 'D', text: 'Fin de priorité' },
    ],
    correct_ids: ['b'],
    explanation: 'Le triangle rouge pointe en bas (cédez le passage) : vous devez laisser passer les usagers prioritaires.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q3',
    chapter_id: 3,
    type: 'sign_recognition',
    question: 'Que signifie un panneau circulaire rouge avec une barre blanche horizontale ?',
    image_key: 'sign_no_entry',
    options: [
      { id: 'a', label: 'A', text: 'Sens unique' },
      { id: 'b', label: 'B', text: 'Sens interdit' },
      { id: 'c', label: 'C', text: 'Interdit aux piétons' },
      { id: 'd', label: 'D', text: 'Stationnement interdit' },
    ],
    correct_ids: ['b'],
    explanation: 'Le disque rouge avec barre blanche = sens interdit. Vous ne pouvez pas entrer.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q4',
    chapter_id: 3,
    type: 'true_false',
    question: 'Un panneau triangulaire à fond blanc avec bordure rouge est un panneau de danger.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Les panneaux triangulaires rouges signalent un danger. Ils vous avertissent d\'un risque à venir.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q5',
    chapter_id: 3,
    type: 'scenario',
    question: 'Quelle est la forme des panneaux d\'interdiction ?',
    options: [
      { id: 'a', label: 'A', text: 'Triangle rouge' },
      { id: 'b', label: 'B', text: 'Cercle rouge' },
      { id: 'c', label: 'C', text: 'Carré bleu' },
      { id: 'd', label: 'D', text: 'Octogone rouge' },
    ],
    correct_ids: ['b'],
    explanation: 'Les panneaux d\'interdiction sont ronds avec un liseré rouge. Ex: interdit de dépasser, sens interdit.',
    difficulty: 'medium',
  },
  {
    id: 'ch3_q6',
    chapter_id: 3,
    type: 'scenario',
    question: 'Quelle est la forme des panneaux d\'obligation ?',
    options: [
      { id: 'a', label: 'A', text: 'Triangle rouge' },
      { id: 'b', label: 'B', text: 'Cercle rouge barré' },
      { id: 'c', label: 'C', text: 'Cercle bleu' },
      { id: 'd', label: 'D', text: 'Rectangle vert' },
    ],
    correct_ids: ['c'],
    explanation: 'Les panneaux d\'obligation sont des cercles bleus. Ils imposent une action obligatoire.',
    difficulty: 'medium',
  },
  {
    id: 'ch3_q7',
    chapter_id: 3,
    type: 'sign_recognition',
    question: 'Que signifie ce panneau ?',
    image_key: 'sign_speed_50',
    options: [
      { id: 'a', label: 'A', text: 'Vitesse minimum 50 km/h' },
      { id: 'b', label: 'B', text: 'Vitesse maximum 50 km/h' },
      { id: 'c', label: 'C', text: 'Fin de limitation à 50 km/h' },
      { id: 'd', label: 'D', text: 'Zone de 50 m' },
    ],
    correct_ids: ['b'],
    explanation: 'Ce panneau rond rouge indique que vous ne pouvez pas dépasser 50 km/h.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q8',
    chapter_id: 3,
    type: 'true_false',
    question: 'Une ligne discontinue au sol peut être franchie pour dépasser.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Une ligne blanche discontinue peut être franchie pour dépasser si la manœuvre est sûre.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q9',
    chapter_id: 3,
    type: 'true_false',
    question: 'On peut dépasser sur une ligne blanche continue.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Une ligne continue ne doit jamais être franchie. Le dépassement est interdit.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q10',
    chapter_id: 3,
    type: 'sign_recognition',
    question: 'Que signifie ce panneau ?',
    image_key: 'sign_pedestrian_crossing',
    options: [
      { id: 'a', label: 'A', text: 'Jeux d\'enfants' },
      { id: 'b', label: 'B', text: 'Passage piétons' },
      { id: 'c', label: 'C', text: 'École' },
      { id: 'd', label: 'D', text: 'Zone de travaux' },
    ],
    correct_ids: ['b'],
    explanation: 'Ce panneau annonce un passage piétons. Ralentissez et cédez le passage aux piétons.',
    difficulty: 'easy',
  },
  {
    id: 'ch3_q11',
    chapter_id: 3,
    type: 'scenario',
    question: 'Que signifie un feu orange (jaune) fixe ?',
    options: [
      { id: 'a', label: 'A', text: 'Accélérez avant le rouge' },
      { id: 'b', label: 'B', text: 'Arrêtez-vous si vous le pouvez en toute sécurité' },
      { id: 'c', label: 'C', text: 'Continuez normalement' },
      { id: 'd', label: 'D', text: 'Priorité aux piétons seulement' },
    ],
    correct_ids: ['b'],
    explanation: 'Le feu orange signifie que le rouge va s\'allumer. Arrêtez-vous si possible, ne tentez pas de passer.',
    difficulty: 'medium',
  },
  {
    id: 'ch3_q12',
    chapter_id: 3,
    type: 'true_false',
    question: 'Un feu rouge clignotant signifie que vous devez vous arrêter et céder la priorité.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Un feu rouge clignotant impose un arrêt et l\'obligation de céder le passage avant de continuer.',
    difficulty: 'medium',
  },
  {
    id: 'ch3_q13',
    chapter_id: 3,
    type: 'sign_recognition',
    question: 'Que signifie ce panneau ?',
    image_key: 'sign_no_overtaking',
    options: [
      { id: 'a', label: 'A', text: 'Dépassement interdit' },
      { id: 'b', label: 'B', text: 'Voie réservée aux bus' },
      { id: 'c', label: 'C', text: 'Fin de toutes interdictions' },
      { id: 'd', label: 'D', text: 'Voiture interdite' },
    ],
    correct_ids: ['a'],
    explanation: 'Ce panneau interdit de dépasser les véhicules devant vous. Respectez cette interdiction.',
    difficulty: 'medium',
  },
  {
    id: 'ch3_q14',
    chapter_id: 3,
    type: 'scenario',
    question: 'Quelle couleur de panneau indique une information de direction ou de service ?',
    options: [
      { id: 'a', label: 'A', text: 'Rouge' },
      { id: 'b', label: 'B', text: 'Orange' },
      { id: 'c', label: 'C', text: 'Bleu' },
      { id: 'd', label: 'D', text: 'Vert (sur autoroute)' },
    ],
    correct_ids: ['d'],
    explanation: 'Les panneaux verts indiquent les directions sur autoroute. Les bleus sont pour les routes nationales.',
    difficulty: 'hard',
  },
  {
    id: 'ch3_q15',
    chapter_id: 3,
    type: 'scenario',
    question: 'Que signifie une croix rouge sur un panneau circulaire ?',
    options: [
      { id: 'a', label: 'A', text: 'Hôpital à proximité' },
      { id: 'b', label: 'B', text: 'Interdiction' },
      { id: 'c', label: 'C', text: 'Zone de secours' },
      { id: 'd', label: 'D', text: 'Passage à niveau' },
    ],
    correct_ids: ['b'],
    explanation: 'Une croix rouge sur un panneau circulaire blanc indique une interdiction spécifique.',
    difficulty: 'hard',
  },
]

// ─── Chapters 4–8: Representative questions (5–8 each for demo) ───────────────

const ch4: QuizQuestion[] = [
  {
    id: 'ch4_q1', chapter_id: 4, type: 'scenario',
    question: 'À une intersection sans signalisation, qui a la priorité ?',
    options: [
      { id: 'a', label: 'A', text: 'Le véhicule venant de droite' },
      { id: 'b', label: 'B', text: 'Le véhicule venant de gauche' },
      { id: 'c', label: 'C', text: 'Le plus gros véhicule' },
      { id: 'd', label: 'D', text: 'Celui qui arrive en premier' },
    ],
    correct_ids: ['a'],
    explanation: 'La règle de base est "priorité à droite" : le véhicule arrivant de votre droite est prioritaire.',
    difficulty: 'easy',
  },
  {
    id: 'ch4_q2', chapter_id: 4, type: 'true_false',
    question: 'Sur un rond-point, les véhicules déjà engagés dans le rond-point sont prioritaires.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Sur un rond-point, cédez le passage aux véhicules circulant déjà dans le rond-point.',
    difficulty: 'easy',
  },
  {
    id: 'ch4_q3', chapter_id: 4, type: 'scenario',
    question: 'Un panneau "Cédez le passage" signifie que vous devez :',
    options: [
      { id: 'a', label: 'A', text: 'Vous arrêter complètement' },
      { id: 'b', label: 'B', text: 'Laisser passer les usagers prioritaires puis avancer' },
      { id: 'c', label: 'C', text: 'Accélérer pour passer avant eux' },
      { id: 'd', label: 'D', text: 'Klaxonner pour signaler votre présence' },
    ],
    correct_ids: ['b'],
    explanation: '"Cédez le passage" vous oblige à laisser passer les autres usagers avant de vous engager.',
    difficulty: 'easy',
  },
  {
    id: 'ch4_q4', chapter_id: 4, type: 'scenario',
    question: 'Un piéton traverse au passage protégé. Que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Klaxonnez pour qu\'il se dépêche' },
      { id: 'b', label: 'B', text: 'Vous arrêtez et attendez qu\'il finisse de traverser' },
      { id: 'c', label: 'C', text: 'Passez doucement derrière lui' },
      { id: 'd', label: 'D', text: 'Signalez avec vos feux' },
    ],
    correct_ids: ['b'],
    explanation: 'Le piéton est prioritaire sur le passage clouté. Arrêtez-vous et attendez.',
    difficulty: 'easy',
  },
  {
    id: 'ch4_q5', chapter_id: 4, type: 'true_false',
    question: 'Un véhicule d\'urgence avec gyrophare et sirène a toujours la priorité.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Les ambulances, pompiers et police ont toujours la priorité. Dégagez immédiatement le passage.',
    difficulty: 'easy',
  },
  {
    id: 'ch4_q6', chapter_id: 4, type: 'scenario',
    question: 'À un carrefour, vous avez un feu vert mais des piétons traversent encore. Que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Avancez car le feu est vert' },
      { id: 'b', label: 'B', text: 'Attendez que les piétons aient fini de traverser' },
      { id: 'c', label: 'C', text: 'Klaxonnez les piétons' },
      { id: 'd', label: 'D', text: 'Passez entre les piétons' },
    ],
    correct_ids: ['b'],
    explanation: 'Même au feu vert, les piétons engagés dans la traversée sont prioritaires.',
    difficulty: 'medium',
  },
  {
    id: 'ch4_q7', chapter_id: 4, type: 'scenario',
    question: 'Deux routes se croisent. Vous êtes sur la route principale (panneau route prioritaire). Qui cède ?',
    options: [
      { id: 'a', label: 'A', text: 'Vous cédez toujours' },
      { id: 'b', label: 'B', text: 'Le véhicule venant de la route secondaire cède' },
      { id: 'c', label: 'C', text: 'La règle de droite s\'applique toujours' },
      { id: 'd', label: 'D', text: 'Personne ne cède' },
    ],
    correct_ids: ['b'],
    explanation: 'Sur une route prioritaire (panneau losange jaune), les véhicules des routes secondaires vous cèdent le passage.',
    difficulty: 'medium',
  },
  {
    id: 'ch4_q8', chapter_id: 4, type: 'scenario',
    question: 'Vous arrivez à un carrefour non signalisé en même temps qu\'un véhicule venant de votre gauche. Qui passe ?',
    options: [
      { id: 'a', label: 'A', text: 'Vous passez (l\'autre vient de gauche)' },
      { id: 'b', label: 'B', text: 'L\'autre passe (il vient de votre gauche)' },
      { id: 'c', label: 'C', text: 'Celui qui arrive en premier' },
      { id: 'd', label: 'D', text: 'Le plus petit véhicule passe' },
    ],
    correct_ids: ['a'],
    explanation: 'Priorité à droite : l\'autre véhicule vient de votre gauche, donc VOUS êtes prioritaire.',
    difficulty: 'medium',
  },
]

const ch5: QuizQuestion[] = [
  {
    id: 'ch5_q1', chapter_id: 5, type: 'scenario',
    question: 'Quelle est la vitesse maximale autorisée en agglomération ?',
    options: [
      { id: 'a', label: 'A', text: '30 km/h' },
      { id: 'b', label: 'B', text: '50 km/h' },
      { id: 'c', label: 'C', text: '70 km/h' },
      { id: 'd', label: 'D', text: '90 km/h' },
    ],
    correct_ids: ['b'],
    explanation: 'La limite en agglomération est 50 km/h sauf indication contraire.',
    difficulty: 'easy',
  },
  {
    id: 'ch5_q2', chapter_id: 5, type: 'true_false',
    question: 'Il est obligatoire d\'allumer ses feux même en plein jour en ville.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'En agglomération de jour, les feux ne sont obligatoires que si la visibilité est inférieure à 50m.',
    difficulty: 'medium',
  },
  {
    id: 'ch5_q3', chapter_id: 5, type: 'scenario',
    question: 'Une zone 30 signifie que vous devez rouler à :',
    options: [
      { id: 'a', label: 'A', text: 'Exactement 30 km/h' },
      { id: 'b', label: 'B', text: 'Maximum 30 km/h' },
      { id: 'c', label: 'C', text: 'Minimum 30 km/h' },
      { id: 'd', label: 'D', text: '30 km/h en semaine seulement' },
    ],
    correct_ids: ['b'],
    explanation: 'En zone 30, la vitesse ne peut pas dépasser 30 km/h. C\'est une limite maximale.',
    difficulty: 'easy',
  },
  {
    id: 'ch5_q4', chapter_id: 5, type: 'scenario',
    question: 'Un bus scolaire à l\'arrêt avec ses feux clignotants. Que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Dépassez lentement' },
      { id: 'b', label: 'B', text: 'Arrêtez-vous et attendez que les enfants soient en sécurité' },
      { id: 'c', label: 'C', text: 'Klaxonnez pour qu\'il dégage' },
      { id: 'd', label: 'D', text: 'Passez de l\'autre côté de la route' },
    ],
    correct_ids: ['b'],
    explanation: 'Ne jamais dépasser un bus scolaire qui charge/décharge des enfants. Attendez qu\'il reparte.',
    difficulty: 'medium',
  },
  {
    id: 'ch5_q5', chapter_id: 5, type: 'true_false',
    question: 'Il est interdit de stationner devant une entrée de garage.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Stationner devant une entrée de garage est interdit car cela bloque l\'accès.',
    difficulty: 'easy',
  },
  {
    id: 'ch5_q6', chapter_id: 5, type: 'scenario',
    question: 'Que signifie une ligne jaune continue au bord de la route ?',
    options: [
      { id: 'a', label: 'A', text: 'Stationnement autorisé' },
      { id: 'b', label: 'B', text: 'Stationnement interdit' },
      { id: 'c', label: 'C', text: 'Voie réservée aux bus' },
      { id: 'd', label: 'D', text: 'Piste cyclable' },
    ],
    correct_ids: ['b'],
    explanation: 'Une ligne jaune continue sur le trottoir signifie que le stationnement et l\'arrêt sont interdits.',
    difficulty: 'medium',
  },
]

const ch6: QuizQuestion[] = [
  {
    id: 'ch6_q1', chapter_id: 6, type: 'step_ordering',
    question: 'Ordonnez les étapes pour se garer en créneau',
    options: [
      { id: 's1', text: 'Mettez le clignotant droit' },
      { id: 's2', text: 'Vérifiez les rétroviseurs et l\'angle mort' },
      { id: 's3', text: 'Reculez en tournant le volant vers la droite' },
      { id: 's4', text: 'Redressez le volant et terminez la manœuvre' },
      { id: 's5', text: 'Serrez le frein à main et coupez le moteur' },
    ],
    correct_ids: ['s1', 's2', 's3', 's4', 's5'],
    explanation: 'La manœuvre en créneau nécessite rigueur et patience. Toujours signaler avant de commencer.',
    difficulty: 'hard',
  },
  {
    id: 'ch6_q2', chapter_id: 6, type: 'true_false',
    question: 'Il est interdit de stationner à moins de 5 m d\'un carrefour.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['true'],
    explanation: 'Pour la visibilité, on ne peut pas stationner à moins de 5 m d\'un carrefour ou d\'un passage piétons.',
    difficulty: 'medium',
  },
  {
    id: 'ch6_q3', chapter_id: 6, type: 'scenario',
    question: 'Avant de reculer, que devez-vous TOUJOURS faire ?',
    options: [
      { id: 'a', label: 'A', text: 'Klaxonner' },
      { id: 'b', label: 'B', text: 'Vérifier que la voie est libre (rétroviseurs + regard direct)' },
      { id: 'c', label: 'C', text: 'Accélérer rapidement' },
      { id: 'd', label: 'D', text: 'Allumer les feux de route' },
    ],
    correct_ids: ['b'],
    explanation: 'Avant toute marche arrière, vérifiez qu\'il n\'y a personne derrière vous.',
    difficulty: 'easy',
  },
  {
    id: 'ch6_q4', chapter_id: 6, type: 'scenario',
    question: 'Combien de fois maximum pouvez-vous effectuer un demi-tour classique (manœuvre en 3 points) ?',
    options: [
      { id: 'a', label: 'A', text: '1 mouvement avant' },
      { id: 'b', label: 'B', text: '3 mouvements (avant-arrière-avant)' },
      { id: 'c', label: 'C', text: '5 mouvements' },
      { id: 'd', label: 'D', text: 'Autant que nécessaire' },
    ],
    correct_ids: ['b'],
    explanation: 'Le demi-tour en 3 points se fait en 3 mouvements : avant à droite, arrière à gauche, avant.',
    difficulty: 'medium',
  },
  {
    id: 'ch6_q5', chapter_id: 6, type: 'true_false',
    question: 'On peut faire demi-tour sur un passage piétons.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Il est interdit de faire demi-tour sur un passage piétons, un carrefour ou une ligne continue.',
    difficulty: 'medium',
  },
]

const ch7: QuizQuestion[] = [
  {
    id: 'ch7_q1', chapter_id: 7, type: 'scenario',
    question: 'Quelle est la règle des 2 secondes ?',
    options: [
      { id: 'a', label: 'A', text: 'Attendez 2 secondes avant de démarrer' },
      { id: 'b', label: 'B', text: 'Laissez 2 secondes de distance avec le véhicule devant' },
      { id: 'c', label: 'C', text: 'Klaxonnez 2 fois avant de dépasser' },
      { id: 'd', label: 'D', text: 'Roulez à 2 vitesses moins que la limite' },
    ],
    correct_ids: ['b'],
    explanation: 'La règle des 2 secondes : un repère fixe doit passer sous le véhicule devant, puis 2 secondes s\'écoulent avant que vous ne le passiez.',
    difficulty: 'easy',
  },
  {
    id: 'ch7_q2', chapter_id: 7, type: 'true_false',
    question: 'Il est permis de dépasser par la droite sur une autoroute.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Sur autoroute, le dépassement ne se fait que par la gauche. Dépasser par la droite est interdit.',
    difficulty: 'medium',
  },
  {
    id: 'ch7_q3', chapter_id: 7, type: 'hazard_detection',
    question: 'Identifiez le danger principal dans cette scène de conduite',
    image_key: 'hazard_pedestrian',
    options: [
      { id: 'a', label: 'A', text: 'Panneau de signalisation' },
      { id: 'b', label: 'B', text: 'Piéton s\'apprêtant à traverser' },
      { id: 'c', label: 'C', text: 'Véhicule garé' },
      { id: 'd', label: 'D', text: 'Feux de carrefour' },
    ],
    correct_ids: ['b'],
    explanation: 'Un piéton s\'apprêtant à traverser est un danger prioritaire. Réduisez la vitesse.',
    difficulty: 'medium',
  },
  {
    id: 'ch7_q4', chapter_id: 7, type: 'scenario',
    question: 'Par temps de pluie, la distance de sécurité doit être :',
    options: [
      { id: 'a', label: 'A', text: 'La même qu\'en temps sec' },
      { id: 'b', label: 'B', text: 'Doublée' },
      { id: 'c', label: 'C', text: 'Triplée' },
      { id: 'd', label: 'D', text: 'Réduite pour rester visible' },
    ],
    correct_ids: ['b'],
    explanation: 'Par temps de pluie, la distance de freinage est doublée. Doublez donc votre distance de sécurité.',
    difficulty: 'medium',
  },
  {
    id: 'ch7_q5', chapter_id: 7, type: 'true_false',
    question: 'On peut dépasser dans un virage si l\'on voit loin devant.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Il est interdit de dépasser dans un virage, même si vous pensez voir loin. C\'est trop dangereux.',
    difficulty: 'easy',
  },
  {
    id: 'ch7_q6', chapter_id: 7, type: 'scenario',
    question: 'Vous voulez dépasser un camion. Avant de vous rabattre, que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Vous rabattez dès que vous voyez son pare-chocs avant' },
      { id: 'b', label: 'B', text: 'Vous attendez de voir le camion entier dans votre rétroviseur' },
      { id: 'c', label: 'C', text: 'Klaxonnez' },
      { id: 'd', label: 'D', text: 'Accélérez pour vous éloigner' },
    ],
    correct_ids: ['b'],
    explanation: 'Ne vous rabattez qu\'une fois que vous voyez le véhicule dépassé entier dans votre rétroviseur intérieur.',
    difficulty: 'hard',
  },
]

const ch8: QuizQuestion[] = [
  {
    id: 'ch8_q1', chapter_id: 8, type: 'step_ordering',
    question: 'Ordonnez les étapes après un accident de la route',
    options: [
      { id: 's1', text: 'Appelez les secours (police, SAMU)' },
      { id: 's2', text: 'Portez votre gilet réfléchissant' },
      { id: 's3', text: 'Activez les feux de détresse' },
      { id: 's4', text: 'Posez le triangle de signalisation' },
      { id: 's5', text: 'Ne déplacez pas les blessés' },
    ],
    correct_ids: ['s3', 's2', 's4', 's5', 's1'],
    explanation: 'Sécurisez d\'abord (feux + gilet + triangle), puis appelez les secours sans déplacer les blessés.',
    difficulty: 'hard',
  },
  {
    id: 'ch8_q2', chapter_id: 8, type: 'scenario',
    question: 'Votre moteur surchauffe (voyant rouge). Que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Continuez à rouler lentement' },
      { id: 'b', label: 'B', text: 'Garez-vous, coupez le moteur et laissez refroidir' },
      { id: 'c', label: 'C', text: 'Ouvrez le radiateur immédiatement' },
      { id: 'd', label: 'D', text: 'Accélérez pour créer un flux d\'air' },
    ],
    correct_ids: ['b'],
    explanation: 'En cas de surchauffe, arrêtez-vous immédiatement, coupez le moteur et attendez 30 min avant d\'ouvrir le capot.',
    difficulty: 'medium',
  },
  {
    id: 'ch8_q3', chapter_id: 8, type: 'true_false',
    question: 'Il faut déplacer un blessé d\'un accident si le véhicule ne prend pas feu.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'Ne jamais déplacer un blessé sauf danger immédiat (incendie). Cela pourrait aggraver les blessures.',
    difficulty: 'medium',
  },
  {
    id: 'ch8_q4', chapter_id: 8, type: 'scenario',
    question: 'Un pneu éclate à grande vitesse. Que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Freinez brutalement' },
      { id: 'b', label: 'B', text: 'Tenez fermement le volant, relâchez l\'accélérateur progressivement et freinez doucement' },
      { id: 'c', label: 'C', text: 'Braquez fortement vers l\'accotement' },
      { id: 'd', label: 'D', text: 'Passez en vitesse inférieure immédiatement' },
    ],
    correct_ids: ['b'],
    explanation: 'En cas d\'éclatement : tenez le volant fermement, relâchez l\'accélérateur graduellement et freinez doucement.',
    difficulty: 'hard',
  },
  {
    id: 'ch8_q5', chapter_id: 8, type: 'scenario',
    question: 'Vos freins ne répondent plus sur une descente. Que faites-vous ?',
    options: [
      { id: 'a', label: 'A', text: 'Sautez du véhicule' },
      { id: 'b', label: 'B', text: 'Utilisez le frein moteur (rétrograder) et le frein à main progressivement' },
      { id: 'c', label: 'C', text: 'Appuyez répétitivement sur la pédale de frein' },
      { id: 'd', label: 'D', text: 'Accélérez pour passer en montée' },
    ],
    correct_ids: ['b'],
    explanation: 'En cas de perte de freins : rétrogradez progressivement et utilisez le frein à main doucement pour ralentir.',
    difficulty: 'hard',
  },
  {
    id: 'ch8_q6', chapter_id: 8, type: 'true_false',
    question: 'En cas d\'incendie du véhicule, il faut rester dans la voiture et appeler les secours.',
    options: [
      { id: 'true', text: '✓ Vrai' },
      { id: 'false', text: '✗ Faux' },
    ],
    correct_ids: ['false'],
    explanation: 'En cas d\'incendie : évacuez immédiatement le véhicule, éloignez-vous et appelez les secours depuis un endroit sûr.',
    difficulty: 'easy',
  },
]

// ─── Chapter 9: Mock Exam (mixed from all chapters) ───────────────────────────

const ch9: QuizQuestion[] = [
  ...ch1.slice(0, 5).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch2.slice(0, 5).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch3.slice(0, 5).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch4.slice(0, 5).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch5.slice(0, 4).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch6.slice(0, 4).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch7.slice(0, 4).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  ...ch8.slice(0, 4).map(q => ({ ...q, chapter_id: 9, id: 'ch9_' + q.id })),
  // Fill to 40
  ...ch1.slice(5, 9).map(q => ({ ...q, chapter_id: 9, id: 'ch9_b_' + q.id })),
  ...ch3.slice(5, 9).map(q => ({ ...q, chapter_id: 9, id: 'ch9_c_' + q.id })),
]

// ─── All Quiz Data ─────────────────────────────────────────────────────────────

const ALL_QUIZZES: Record<number, QuizQuestion[]> = {
  1: ch1,
  2: ch2,
  3: ch3,
  4: ch4,
  5: ch5,
  6: ch6,
  7: ch7,
  8: ch8,
  9: ch9,
}

export function getChapterQuizzes(chapterId: number): QuizQuestion[] {
  return ALL_QUIZZES[chapterId] ?? []
}

export function getQuizById(id: string): QuizQuestion | undefined {
  for (const quizzes of Object.values(ALL_QUIZZES)) {
    const found = quizzes.find(q => q.id === id)
    if (found) return found
  }
  return undefined
}

// Shuffle helper
export function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
