import { Module, Lesson, Question } from './types'

export const MODULES: Module[] = [
  { id: 'm1', title_fr: 'La signalisation routière', description_fr: 'Panneaux de danger, d\'interdiction, d\'obligation et d\'indication', icon_emoji: '🚦', order_index: 1, is_active: true },
  { id: 'm2', title_fr: 'Les règles de priorité', description_fr: 'Carrefours, giratoires et voies rapides', icon_emoji: '⬆️', order_index: 2, is_active: true },
  { id: 'm3', title_fr: 'Conduite en agglomération', description_fr: 'Limites de vitesse, discipline de voie, zones piétonnes', icon_emoji: '🏙️', order_index: 3, is_active: true },
  { id: 'm4', title_fr: 'La sécurité routière', description_fr: 'Ceintures, distances de sécurité et dépassement', icon_emoji: '🛡️', order_index: 4, is_active: true },
  { id: 'm5', title_fr: 'Feux & marquages au sol', description_fr: 'Phases des feux, marquages routiers et passages piétons', icon_emoji: '🟡', order_index: 5, is_active: true },
  { id: 'm6', title_fr: 'Situations d\'urgence', description_fr: 'Procédures de panne, réponse aux accidents', icon_emoji: '🚨', order_index: 6, is_active: true },
  { id: 'm7', title_fr: 'Mécanique de base', description_fr: 'Vérifications avant départ, mécanique de base, pneumatiques', icon_emoji: '🔧', order_index: 7, is_active: true },
  { id: 'm8', title_fr: 'La réglementation', description_fr: 'Documents obligatoires, alcool au volant, téléphone', icon_emoji: '📋', order_index: 8, is_active: true },
]

export const LESSONS: Lesson[] = [
  // Module 1 — Signalisation
  { id: 'l1_1', module_id: 'm1', title_fr: 'Les panneaux de danger', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Reconnaître les panneaux de danger', body: 'Les panneaux de danger ont une forme triangulaire avec un fond blanc et un liseré rouge. Ils avertissent l\'automobiliste d\'un danger sur la route.' }, { heading: 'Les panneaux courants', body: 'Parmi les panneaux de danger les plus fréquents au Togo, on retrouve : le virage à droite (ou à gauche), le double virage, le rétrécissement de chaussée, et le passage d\'animaux domestiques.' }, { heading: 'Conduite à adopter', body: 'Lorsque vous apercevez un panneau de danger, réduisez votre vitesse, restez vigilant et adaptez votre conduite à la situation annoncée.' }] } },
  { id: 'l1_2', module_id: 'm1', title_fr: 'Les panneaux d\'interdiction', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Forme et couleur', body: 'Les panneaux d\'interdiction sont ronds avec un fond blanc et un liseré rouge. Ils indiquent une interdiction absolue pour tous les usagers.' }, { heading: 'Exemples courants', body: 'Accès interdit, sens interdit, interdiction de dépasser, limitation de vitesse (30, 50, 70 km/h selon la zone).' }, { heading: 'Sanctions', body: 'Le non-respect d\'un panneau d\'interdiction constitue une infraction grave pouvant entraîner une amende et le retrait de points de permis.' }] } },
  { id: 'l1_3', module_id: 'm1', title_fr: 'Les panneaux d\'obligation', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Caractéristiques', body: 'Les panneaux d\'obligation sont ronds à fond bleu. Ils imposent une action précise au conducteur : tourner à droite, aller tout droit, respecter une vitesse minimale.' }, { heading: 'Différence avec les panneaux d\'indication', body: 'Contrairement aux panneaux d\'indication (carrés bleus), les panneaux d\'obligation sont impératifs. Vous devez obligatoirement obéir à leur prescription.' }] } },
  { id: 'l1_4', module_id: 'm1', title_fr: 'Les panneaux d\'indication', order_index: 4, coins_reward: 5, content_json: { sections: [{ heading: 'Rôle des panneaux d\'indication', body: 'Ces panneaux, généralement rectangulaires ou carrés à fond bleu ou vert, fournissent des informations utiles : direction, distance, services disponibles.' }, { heading: 'Panneaux de direction', body: 'Les panneaux verts sont utilisés sur les routes nationales et indiquent les villes principales. Les panneaux bleus signalent les autoroutes.' }] } },

  // Module 2 — Priorités
  { id: 'l2_1', module_id: 'm2', title_fr: 'La priorité à droite', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Le principe fondamental', body: 'En l\'absence de signalisation, vous devez céder le passage à tout véhicule venant de votre droite. C\'est la règle de base aux intersections.' }, { heading: 'Exceptions', body: 'La priorité à droite ne s\'applique pas sur les routes prioritaires (panneaux "route prioritaire" ou "passage protégé"), ni aux véhicules d\'urgence.' }] } },
  { id: 'l2_2', module_id: 'm2', title_fr: 'Les carrefours et giratoires', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Comportement au carrefour', body: 'À l\'approche d\'un carrefour, réduisez votre vitesse, observez la signalisation et cédez le passage si nécessaire avant de vous engager.' }, { heading: 'Le giratoire', body: 'Dans un giratoire, les véhicules déjà engagés dans le rond-point sont prioritaires. Vous devez céder le passage avant d\'entrer dans le giratoire, sauf signalisation contraire.' }] } },
  { id: 'l2_3', module_id: 'm2', title_fr: 'Les voies rapides et routes nationales', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Insertion sur voie rapide', body: 'Pour vous insérer sur une voie rapide, accélérez sur la voie d\'accélération jusqu\'à atteindre la vitesse du trafic, puis trouvez un créneau sûr pour vous insérer.' }, { heading: 'Priorité des véhicules lents', body: 'Sur les routes nationales, les véhicules lents (tracteurs, engins agricoles) doivent se déporter à droite pour faciliter le dépassement des autres usagers.' }] } },

  // Module 3 — Conduite
  { id: 'l3_1', module_id: 'm3', title_fr: 'Vitesses en agglomération', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Limites de vitesse urbaines', body: 'En agglomération (zones habitées signalées), la vitesse maximale est de 50 km/h. Près des écoles et dans les zones résidentielles, cette limite peut être réduite à 30 km/h.' }, { heading: 'Adaptation de la vitesse', body: 'Au-delà des limites légales, vous devez toujours adapter votre vitesse aux conditions : météo, visibilité, état de la route, densité du trafic.' }] } },
  { id: 'l3_2', module_id: 'm3', title_fr: 'Discipline de voie', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Choix de voie', body: 'Sur une route à plusieurs voies, les voies de gauche sont réservées au dépassement. Vous devez regagner la voie de droite après avoir dépassé.' }, { heading: 'Changement de voie', body: 'Avant tout changement de voie, activez votre clignotant, vérifiez vos rétroviseurs et l\'angle mort, puis effectuez le changement progressivement.' }] } },
  { id: 'l3_3', module_id: 'm3', title_fr: 'Zones piétonnes et passages cloutés', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Priorité aux piétons', body: 'Les piétons engagés sur un passage piéton sont absolument prioritaires. Vous devez vous arrêter et attendre qu\'ils aient entièrement traversé.' }, { heading: 'Zones piétonnes', body: 'Dans les zones piétonnes, la circulation des véhicules est interdite aux heures indiquées. Seuls les riverains autorisés peuvent y accéder, au pas.' }] } },
  { id: 'l3_4', module_id: 'm3', title_fr: 'Vitesses hors agglomération', order_index: 4, coins_reward: 5, content_json: { sections: [{ heading: 'Routes nationales', body: 'Hors agglomération sur route à deux voies, la vitesse maximale est de 90 km/h. Cette limite est réduite à 80 km/h par temps de pluie.' }, { heading: 'Autoroutes et voies rapides', body: 'Sur les autoroutes et voies express, la vitesse maximale est de 110 km/h. Un minimum de 80 km/h est requis sur la voie gauche.' }] } },

  // Module 4 — Sécurité
  { id: 'l4_1', module_id: 'm4', title_fr: 'La ceinture de sécurité', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Obligation légale', body: 'Le port de la ceinture de sécurité est obligatoire pour le conducteur et tous les passagers, à l\'avant comme à l\'arrière du véhicule.' }, { heading: 'Efficacité', body: 'En cas de choc frontal, la ceinture réduit le risque de mort de 45 %. Sans ceinture, un passager peut être éjecté du véhicule, même à faible vitesse.' }] } },
  { id: 'l4_2', module_id: 'm4', title_fr: 'Les distances de sécurité', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Règle des deux secondes', body: 'Maintenez une distance d\'au moins deux secondes avec le véhicule qui vous précède. Par temps de pluie ou de nuit, doublez cette distance.' }, { heading: 'Calcul pratique', body: 'Choisissez un repère fixe (poteau, arbre). Quand le véhicule devant vous le dépasse, comptez "mille et un, mille et deux". Vous devez dépasser ce repère seulement après.' }] } },
  { id: 'l4_3', module_id: 'm4', title_fr: 'Le dépassement', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Conditions du dépassement', body: 'Avant de dépasser : vérifiez que la route est libre loin devant, que le dépassement est autorisé (pas de ligne continue), que vous avez une vitesse suffisante.' }, { heading: 'Manœuvre de dépassement', body: 'Signalez votre intention, accelerez, dépassez rapidement, signalez votre retour, rabattez-vous à distance suffisante du véhicule dépassé.' }] } },

  // Module 5 — Feux
  { id: 'l5_1', module_id: 'm5', title_fr: 'Les feux tricolores', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Signification des couleurs', body: 'Feu vert : vous pouvez avancer. Feu orange : préparez-vous à vous arrêter (si vous êtes trop proche, passez prudemment). Feu rouge : arrêt obligatoire avant la ligne.' }, { heading: 'Feux spéciaux', body: 'Une flèche verte clignotante autorise le tournant indiqué même au feu rouge. Une flèche rouge indique une interdiction spécifique de direction.' }] } },
  { id: 'l5_2', module_id: 'm5', title_fr: 'Les marquages au sol', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Lignes continues et discontinues', body: 'Une ligne blanche continue ne doit jamais être franchie. Une ligne discontinue peut être franchie pour dépasser ou changer de voie si la sécurité le permet.' }, { heading: 'Autres marquages', body: 'Les passages piétons sont marqués de bandes blanches parallèles. Les cases d\'arrêt de bus sont délimitées par des marquages jaunes.' }] } },
  { id: 'l5_3', module_id: 'm5', title_fr: 'Traversées et passages à niveau', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Passage à niveau', body: 'Ralentissez dès l\'approche d\'un passage à niveau. À l\'approche des feux clignotants ou d\'une barrière, arrêtez-vous. Ne franchissez jamais les barrières.' }, { heading: 'Traversées de tramway', body: 'Ne vous engagez pas sur les voies de tramway si vous risquez d\'y rester bloqué. Cédez toujours le passage au tramway.' }] } },

  // Module 6 — Urgences
  { id: 'l6_1', module_id: 'm6', title_fr: 'Procédures en cas de panne', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Immobilisation en sécurité', body: 'En cas de panne, actionnez les feux de détresse immédiatement. Garez-vous sur le côté droit de la route, le plus loin possible de la circulation.' }, { heading: 'Signalisation du véhicule', body: 'Sortez du véhicule par le côté passager (côté opposé à la circulation). Placez le triangle de signalisation à 30 m en agglomération, 100 m hors agglomération.' }] } },
  { id: 'l6_2', module_id: 'm6', title_fr: 'Comportement en cas d\'accident', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Les 4 actions PSAM', body: 'Protéger (sécuriser la zone), Secourir (porter assistance sans déplacer les blessés si possible), Alerter (appeler le 18 ou le 112), Maintenir (rester sur place jusqu\'à l\'arrivée des secours).' }, { heading: 'Ce qu\'il ne faut pas faire', body: 'Ne déplacez pas un blessé sauf danger imminent. Ne donnez rien à boire. Ne retirez pas le casque d\'un motard sauf s\'il ne respire pas.' }] } },
  { id: 'l6_3', module_id: 'm6', title_fr: 'Numéros d\'urgence au Togo', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Numéros à connaître', body: 'Police secours : 17. Pompiers : 18. SAMU / urgences médicales : 15. Numéro d\'urgence européen universel (fonctionne au Togo) : 112.' }, { heading: 'Constat amiable', body: 'En cas d\'accident sans blessés, remplissez un constat amiable avec l\'autre conducteur. Notez les plaques, noms, assurances. Ne reconnaissez aucune responsabilité oralement.' }] } },

  // Module 7 — Mécanique
  { id: 'l7_1', module_id: 'm7', title_fr: 'Vérifications avant départ', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Les 4 niveaux à vérifier', body: 'Avant un long trajet, vérifiez : le niveau d\'huile moteur, le niveau de liquide de refroidissement, le niveau de liquide de frein, le niveau du lave-glace.' }, { heading: 'Les pneumatiques', body: 'Vérifiez la pression des pneus à froid (la valeur recommandée est indiquée dans le manuel du véhicule). Vérifiez également l\'usure : la rainure doit dépasser 1,6 mm.' }] } },
  { id: 'l7_2', module_id: 'm7', title_fr: 'Les pneumatiques', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Pression des pneus', body: 'Une pression insuffisante augmente la consommation de carburant, la distance de freinage et le risque d\'éclatement. Vérifiez la pression toutes les 4 semaines.' }, { heading: 'Usure et remplacement', body: 'Les témoins d\'usure (petits picots dans les rainures) indiquent le seuil légal minimal. Un pneu usé est dangereux, surtout sur route mouillée.' }] } },
  { id: 'l7_3', module_id: 'm7', title_fr: 'Éclairages et équipements', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Feux obligatoires', body: 'Vérifiez régulièrement le bon fonctionnement de tous vos feux : phares, feux de position, feux stop, clignotants et feux de recul.' }, { heading: 'Équipements obligatoires', body: 'Dans le véhicule doivent se trouver : un triangle de signalisation, un gilet de sécurité fluorescent, un extincteur (recommandé), une trousse de secours.' }] } },

  // Module 8 — Réglementation
  { id: 'l8_1', module_id: 'm8', title_fr: 'Documents obligatoires', order_index: 1, coins_reward: 5, content_json: { sections: [{ heading: 'Ce que vous devez avoir', body: 'Un conducteur doit toujours avoir sur lui : son permis de conduire valide, la carte grise du véhicule (certificat d\'immatriculation), l\'attestation d\'assurance en cours de validité.' }, { heading: 'Contrôle de police', body: 'En cas de contrôle, présentez calmement vos documents. Ne discutez pas d\'une infraction sur place — les recours légaux existent.' }] } },
  { id: 'l8_2', module_id: 'm8', title_fr: 'Alcool et drogues au volant', order_index: 2, coins_reward: 5, content_json: { sections: [{ heading: 'Taux légal d\'alcoolémie', body: 'Le taux maximal légal d\'alcool dans le sang est de 0,5 g/L au Togo (0,2 g/L pour les conducteurs professionnels et les nouveaux permis). Au-delà, vous êtes en infraction.' }, { heading: 'Effets de l\'alcool', body: 'L\'alcool allonge le temps de réaction, réduit le champ visuel, et crée un sentiment de fausse confiance. Même un verre peut altérer les réflexes.' }] } },
  { id: 'l8_3', module_id: 'm8', title_fr: 'Téléphone et distracteurs', order_index: 3, coins_reward: 5, content_json: { sections: [{ heading: 'Téléphone au volant', body: 'L\'utilisation du téléphone tenu en main est strictement interdite pendant la conduite. Seuls les kits mains libres sont autorisés — mais restent déconseillés.' }, { heading: 'Autres distracteurs', body: 'Manger, régler la radio, discuter avec des passagers ou regarder une carte sont autant de sources de distraction. Arrêtez-vous dans un endroit sûr si nécessaire.' }] } },
]

export const QUESTIONS: Question[] = [
  // Module 1 questions
  { id: 'q1_1', module_id: 'm1', question_text: 'Quelle est la forme d\'un panneau de danger ?', option_a: 'Ronde à fond bleu', option_b: 'Triangulaire à fond blanc et liseré rouge', option_c: 'Rectangulaire à fond vert', option_d: 'Carrée à fond jaune', correct_option: 'b', explanation: 'Les panneaux de danger sont triangulaires avec un fond blanc et un liseré rouge. Ils avertissent d\'un danger à venir.', difficulty: 'easy' },
  { id: 'q1_2', module_id: 'm1', question_text: 'Un panneau rond à fond blanc avec un liseré rouge signifie :', option_a: 'Une indication de direction', option_b: 'Une obligation à respecter', option_c: 'Une interdiction', option_d: 'Un danger', correct_option: 'c', explanation: 'Les panneaux d\'interdiction sont ronds, à fond blanc avec un liseré rouge.', difficulty: 'easy' },
  { id: 'q1_3', module_id: 'm1', question_text: 'Un panneau rond à fond bleu indique :', option_a: 'Un danger', option_b: 'Une interdiction', option_c: 'Une obligation', option_d: 'Un service', correct_option: 'c', explanation: 'Les panneaux d\'obligation sont ronds à fond bleu. Ils imposent une action précise au conducteur.', difficulty: 'easy' },
  { id: 'q1_4', module_id: 'm1', question_text: 'Que signifie un panneau triangulaire représentant deux voitures côte à côte avec un X rouge ?', option_a: 'Voie réservée aux deux-roues', option_b: 'Interdiction de dépasser', option_c: 'Route dangereuse', option_d: 'Travaux à venir', correct_option: 'b', explanation: 'Ce panneau d\'interdiction signifie qu\'il est interdit de dépasser dans cette zone.', difficulty: 'medium' },
  { id: 'q1_5', module_id: 'm1', question_text: 'Sur une route nationale, la couleur des panneaux de direction est :', option_a: 'Bleue', option_b: 'Verte', option_c: 'Jaune', option_d: 'Blanche', correct_option: 'b', explanation: 'Les panneaux de direction sur route nationale sont de couleur verte. Le bleu est réservé aux autoroutes.', difficulty: 'medium' },

  // Module 2 questions
  { id: 'q2_1', module_id: 'm2', question_text: 'En l\'absence de signalisation à un carrefour, vous devez céder le passage :', option_a: 'Aux véhicules venant de gauche', option_b: 'Aux véhicules venant de droite', option_c: 'À tous les véhicules', option_d: 'Aux véhicules les plus rapides', correct_option: 'b', explanation: 'La règle de base est la priorité à droite. En l\'absence de signalisation, vous cédez le passage aux véhicules venant de votre droite.', difficulty: 'easy' },
  { id: 'q2_2', module_id: 'm2', question_text: 'Dans un giratoire, qui est prioritaire ?', option_a: 'Les véhicules entrant dans le giratoire', option_b: 'Les véhicules déjà dans le giratoire', option_c: 'Les véhicules venant de droite', option_d: 'Les poids lourds', correct_option: 'b', explanation: 'Dans un giratoire, les véhicules déjà engagés sont prioritaires. Vous devez céder le passage avant d\'entrer.', difficulty: 'easy' },
  { id: 'q2_3', module_id: 'm2', question_text: 'La règle de priorité à droite s\'applique-t-elle sur une route marquée "route prioritaire" ?', option_a: 'Oui, toujours', option_b: 'Non, les véhicules sur la route prioritaire ont la priorité', option_c: 'Seulement la nuit', option_d: 'Seulement en agglomération', correct_option: 'b', explanation: 'Sur une route prioritaire (signalée par panneau), les véhicules circulant sur cette route ont la priorité sur les véhicules des voies secondaires.', difficulty: 'medium' },
  { id: 'q2_4', module_id: 'm2', question_text: 'Pour vous insérer sur une voie rapide, vous devez :', option_a: 'Vous arrêter et attendre un créneau', option_b: 'Accélérer sur la bretelle d\'accélération et vous insérer progressivement', option_c: 'Klaxonner pour prévenir les autres conducteurs', option_d: 'Rouler lentement sur la voie d\'urgence', correct_option: 'b', explanation: 'Pour s\'insérer sur voie rapide, il faut accélérer sur la voie d\'accélération jusqu\'à la vitesse du trafic, puis trouver un créneau sûr.', difficulty: 'medium' },
  { id: 'q2_5', module_id: 'm2', question_text: 'Vous arrivez à un carrefour non signalisé. Une voiture arrive sur votre droite. Que faites-vous ?', option_a: 'Vous continuez car vous êtes sur une grande route', option_b: 'Vous klaxonnez pour la prévenir', option_c: 'Vous lui cédez le passage', option_d: 'Vous accélérez pour passer en premier', correct_option: 'c', explanation: 'La règle de priorité à droite s\'applique : vous devez céder le passage au véhicule venant de votre droite.', difficulty: 'easy' },

  // Module 3 questions
  { id: 'q3_1', module_id: 'm3', question_text: 'Quelle est la vitesse maximale en agglomération au Togo ?', option_a: '30 km/h', option_b: '50 km/h', option_c: '70 km/h', option_d: '90 km/h', correct_option: 'b', explanation: 'En agglomération, la vitesse maximale autorisée est de 50 km/h, sauf indication contraire (zones 30 near écoles).', difficulty: 'easy' },
  { id: 'q3_2', module_id: 'm3', question_text: 'Sur une route à deux voies hors agglomération, la vitesse maximale est de :', option_a: '70 km/h', option_b: '80 km/h', option_c: '90 km/h', option_d: '110 km/h', correct_option: 'c', explanation: 'Sur route nationale à deux voies hors agglomération, la vitesse maximale est de 90 km/h (80 km/h par temps de pluie).', difficulty: 'easy' },
  { id: 'q3_3', module_id: 'm3', question_text: 'Un piéton est engagé sur un passage piéton. Que faites-vous ?', option_a: 'Vous klaxonnez pour lui signaler votre présence', option_b: 'Vous ralentissez et passez derrière lui', option_c: 'Vous vous arrêtez et attendez qu\'il finisse de traverser', option_d: 'Vous continuez en ralentissant légèrement', correct_option: 'c', explanation: 'Le piéton engagé sur un passage piéton est absolument prioritaire. Vous devez vous arrêter et attendre qu\'il ait entièrement traversé.', difficulty: 'easy' },
  { id: 'q3_4', module_id: 'm3', question_text: 'Sur une route à plusieurs voies, les voies de gauche sont :', option_a: 'Réservées aux véhicules lents', option_b: 'Réservées au dépassement', option_c: 'Interdites aux voitures de tourisme', option_d: 'Réservées aux urgences', correct_option: 'b', explanation: 'Sur route multi-voies, les voies de gauche sont réservées au dépassement. Vous devez regagner la droite après avoir dépassé.', difficulty: 'medium' },
  { id: 'q3_5', module_id: 'm3', question_text: 'Avant de changer de voie, vous devez :', option_a: 'Accélérer fortement', option_b: 'Klaxonner', option_c: 'Activer le clignotant et vérifier les rétroviseurs et l\'angle mort', option_d: 'Seulement regarder dans le rétroviseur central', correct_option: 'c', explanation: 'Avant tout changement de voie, il faut activer le clignotant, vérifier les rétroviseurs ET l\'angle mort, puis effectuer le changement progressivement.', difficulty: 'medium' },

  // Module 4 questions
  { id: 'q4_1', module_id: 'm4', question_text: 'Le port de la ceinture de sécurité est obligatoire :', option_a: 'Uniquement pour le conducteur', option_b: 'Pour le conducteur et les passagers avant', option_c: 'Pour tous les occupants du véhicule', option_d: 'Seulement sur autoroute', correct_option: 'c', explanation: 'Le port de la ceinture est obligatoire pour TOUS les occupants du véhicule, conducteur et passagers, à l\'avant comme à l\'arrière.', difficulty: 'easy' },
  { id: 'q4_2', module_id: 'm4', question_text: 'Quelle est la règle des "deux secondes" en conduite ?', option_a: 'Attendre 2 secondes au feu vert avant de démarrer', option_b: 'Maintenir 2 secondes de distance avec le véhicule devant', option_c: 'Vérifier les rétroviseurs toutes les 2 secondes', option_d: 'Signaler 2 secondes avant de tourner', correct_option: 'b', explanation: 'La règle des 2 secondes signifie qu\'il doit s\'écouler au moins 2 secondes entre le moment où le véhicule devant passe un repère et celui où vous le passez.', difficulty: 'easy' },
  { id: 'q4_3', module_id: 'm4', question_text: 'Par temps de pluie, la distance de sécurité doit être :', option_a: 'La même qu\'en temps sec', option_b: 'Réduite car les pneus adhèrent mieux', option_c: 'Doublée par rapport au temps sec', option_d: 'De 10 mètres minimum', correct_option: 'c', explanation: 'Par temps de pluie (ou de nuit), vous devez doubler la distance de sécurité car la distance de freinage est beaucoup plus longue sur route mouillée.', difficulty: 'medium' },
  { id: 'q4_4', module_id: 'm4', question_text: 'Avant de dépasser, vous devez vérifier :', option_a: 'Uniquement que la route est libre devant vous', option_b: 'Que le dépassement est autorisé, la route libre devant et derrière, votre vitesse suffisante', option_c: 'Seulement que personne ne vous suit', option_d: 'Que vous avez de l\'essence', correct_option: 'b', explanation: 'Avant de dépasser, vérifiez que c\'est autorisé (pas de ligne continue), que la route est libre devant et derrière, et que vous avez une vitesse suffisante pour compléter la manœuvre.', difficulty: 'medium' },
  { id: 'q4_5', module_id: 'm4', question_text: 'La ceinture de sécurité réduit le risque de mort en cas de choc frontal de :', option_a: '15 %', option_b: '30 %', option_c: '45 %', option_d: '60 %', correct_option: 'c', explanation: 'La ceinture de sécurité réduit le risque de mort de 45 % en cas de choc frontal. Elle est le dispositif de sécurité le plus efficace.', difficulty: 'medium' },

  // Module 5 questions
  { id: 'q5_1', module_id: 'm5', question_text: 'Vous arrivez à un feu orange. Que faites-vous ?', option_a: 'Vous accélérez pour passer avant le rouge', option_b: 'Vous ralentissez et vous arrêtez si vous le pouvez en toute sécurité', option_c: 'Vous ignorez le feu s\'il n\'y a pas de voiture', option_d: 'Vous klaxonnez', correct_option: 'b', explanation: 'Le feu orange signifie "préparez-vous à vous arrêter". Si vous êtes trop proche de la ligne, vous pouvez passer prudemment.', difficulty: 'easy' },
  { id: 'q5_2', module_id: 'm5', question_text: 'Une ligne blanche continue au centre de la route signifie :', option_a: 'Vous pouvez la franchir pour dépasser avec précaution', option_b: 'Elle ne doit jamais être franchie', option_c: 'Elle peut être franchie uniquement à droite', option_d: 'Elle marque une voie de bus', correct_option: 'b', explanation: 'Une ligne blanche continue ne doit JAMAIS être franchie. Elle indique une zone de dépassement interdit.', difficulty: 'easy' },
  { id: 'q5_3', module_id: 'm5', question_text: 'À un passage à niveau avec feux clignotants allumés, vous devez :', option_a: 'Ralentir et passer rapidement', option_b: 'Klaxonner et passer', option_c: 'Vous arrêter et ne pas passer', option_d: 'Vérifier si un train arrive avant de passer', correct_option: 'c', explanation: 'Des feux clignotants à un passage à niveau signifient qu\'un train approche. Vous devez absolument vous arrêter et attendre.', difficulty: 'easy' },
  { id: 'q5_4', module_id: 'm5', question_text: 'Une flèche verte clignotante au feu signifie :', option_a: 'Vous pouvez avancer dans la direction indiquée même au feu rouge', option_b: 'Vous devez vous arrêter', option_c: 'La voie est réservée aux bus', option_d: 'Travaux en cours', correct_option: 'a', explanation: 'Une flèche verte clignotante autorise le tournant indiqué même si le feu général est rouge, en cédant le passage aux autres usagers.', difficulty: 'medium' },
  { id: 'q5_5', module_id: 'm5', question_text: 'Les témoins d\'usure d\'un pneu indiquent :', option_a: 'La pression du pneu', option_b: 'L\'âge du pneu', option_c: 'Le seuil légal minimal d\'usure', option_d: 'La vitesse maximale autorisée', correct_option: 'c', explanation: 'Les témoins d\'usure (picots dans les rainures) indiquent le seuil légal de 1,6 mm. En dessous, le pneu est dangereux et doit être remplacé.', difficulty: 'medium' },

  // Module 6 questions
  { id: 'q6_1', module_id: 'm6', question_text: 'En cas de panne sur la route, vous devez d\'abord :', option_a: 'Sortir du véhicule par la gauche', option_b: 'Activer les feux de détresse et vous garer sur le côté droit', option_c: 'Appeler immédiatement la police', option_d: 'Pousser le véhicule sur le côté', correct_option: 'b', explanation: 'En cas de panne, actionnez les feux de détresse immédiatement et garez-vous sur le côté droit de la route, aussi loin que possible de la circulation.', difficulty: 'easy' },
  { id: 'q6_2', module_id: 'm6', question_text: 'Hors agglomération, à quelle distance placez-vous le triangle de signalisation en cas de panne ?', option_a: '10 mètres', option_b: '30 mètres', option_c: '100 mètres', option_d: '200 mètres', correct_option: 'c', explanation: 'Hors agglomération, le triangle de signalisation doit être placé à 100 mètres du véhicule immobilisé. En ville, 30 mètres suffisent.', difficulty: 'medium' },
  { id: 'q6_3', module_id: 'm6', question_text: 'Quel est le numéro des pompiers au Togo ?', option_a: '15', option_b: '17', option_c: '18', option_d: '112', correct_option: 'c', explanation: 'Le numéro des pompiers est le 18. Le 17 est la police secours, le 15 le SAMU, et le 112 est le numéro d\'urgence universel.', difficulty: 'easy' },
  { id: 'q6_4', module_id: 'm6', question_text: 'Les 4 actions à effectuer en cas d\'accident (PSAM) sont :', option_a: 'Photographier, Sauvegarder, Appeler, Médiatiser', option_b: 'Protéger, Secourir, Alerter, Maintenir', option_c: 'Penser, Signaler, Aider, Marquer', option_d: 'Partir, Sauver, Arrêter, Menacer', correct_option: 'b', explanation: 'PSAM = Protéger (sécuriser la zone), Secourir (porter assistance), Alerter (appeler les secours), Maintenir (rester sur place).', difficulty: 'medium' },
  { id: 'q6_5', module_id: 'm6', question_text: 'En cas d\'accident, pouvez-vous déplacer un blessé ?', option_a: 'Oui, toujours pour le mettre en sécurité', option_b: 'Non, sauf en cas de danger imminent (incendie, noyade...)', option_c: 'Oui, pour le mettre en position assise', option_d: 'Non, jamais dans aucun cas', correct_option: 'b', explanation: 'Ne déplacez pas un blessé sauf si un danger imminent (incendie, véhicule qui arrive...) l\'impose. Bouger un blessé peut aggraver ses blessures.', difficulty: 'medium' },

  // Module 7 questions
  { id: 'q7_1', module_id: 'm7', question_text: 'Quelle est la profondeur minimale légale des rainures d\'un pneu ?', option_a: '0,5 mm', option_b: '1,6 mm', option_c: '3 mm', option_d: '5 mm', correct_option: 'b', explanation: 'La profondeur minimale légale des rainures d\'un pneu est de 1,6 mm. C\'est la valeur indiquée par les témoins d\'usure.', difficulty: 'medium' },
  { id: 'q7_2', module_id: 'm7', question_text: 'À quelle fréquence devez-vous vérifier la pression de vos pneus ?', option_a: 'Tous les jours', option_b: 'Toutes les 2 semaines', option_c: 'Toutes les 4 semaines', option_d: 'Tous les 6 mois', correct_option: 'c', explanation: 'Il est recommandé de vérifier la pression des pneus à froid toutes les 4 semaines et avant tout long trajet.', difficulty: 'easy' },
  { id: 'q7_3', module_id: 'm7', question_text: 'Parmi ces équipements, lequel est obligatoire dans un véhicule au Togo ?', option_a: 'Un extincteur', option_b: 'Un triangle de signalisation', option_c: 'Une trousse de secours complète', option_d: 'Un câble de démarrage', correct_option: 'b', explanation: 'Le triangle de signalisation et le gilet de sécurité fluorescent sont obligatoires. L\'extincteur et la trousse de secours sont fortement recommandés.', difficulty: 'medium' },
  { id: 'q7_4', module_id: 'm7', question_text: 'Quels niveaux devez-vous vérifier avant un long trajet ?', option_a: 'Huile moteur seulement', option_b: 'Huile moteur et carburant', option_c: 'Huile moteur, liquide de refroidissement, liquide de frein, lave-glace', option_d: 'Uniquement le carburant', correct_option: 'c', explanation: 'Avant un long trajet, vérifiez : le niveau d\'huile moteur, de liquide de refroidissement, de liquide de frein et de lave-glace.', difficulty: 'easy' },
  { id: 'q7_5', module_id: 'm7', question_text: 'Une pression insuffisante dans les pneus entraîne :', option_a: 'Une meilleure adhérence', option_b: 'Une réduction de la consommation', option_c: 'Une augmentation de la distance de freinage et du risque d\'éclatement', option_d: 'Aucun effet notable', correct_option: 'c', explanation: 'Un pneu sous-gonflé augmente la consommation de carburant, la distance de freinage et le risque d\'éclatement, surtout en été.', difficulty: 'medium' },

  // Module 8 questions
  { id: 'q8_1', module_id: 'm8', question_text: 'Quel est le taux maximal légal d\'alcool dans le sang au Togo ?', option_a: '0,2 g/L', option_b: '0,5 g/L', option_c: '0,8 g/L', option_d: '1,0 g/L', correct_option: 'b', explanation: 'Le taux légal maximal d\'alcoolémie au Togo est de 0,5 g/L de sang. Pour les conducteurs professionnels et les nouveaux permis, c\'est 0,2 g/L.', difficulty: 'easy' },
  { id: 'q8_2', module_id: 'm8', question_text: 'Lequel de ces documents N\'est PAS obligatoire pour conduire ?', option_a: 'Le permis de conduire', option_b: 'La carte grise (certificat d\'immatriculation)', option_c: 'L\'attestation d\'assurance', option_d: 'Le carnet d\'entretien du véhicule', correct_option: 'd', explanation: 'Le carnet d\'entretien est recommandé mais non obligatoire. Les documents obligatoires sont : permis de conduire, carte grise et attestation d\'assurance.', difficulty: 'easy' },
  { id: 'q8_3', module_id: 'm8', question_text: 'L\'utilisation du téléphone tenu en main pendant la conduite est :', option_a: 'Autorisée à faible vitesse', option_b: 'Autorisée à l\'arrêt au feu rouge', option_c: 'Toujours strictement interdite', option_d: 'Autorisée si vous utilisez le haut-parleur', correct_option: 'c', explanation: 'L\'utilisation du téléphone tenu en main est strictement interdite pendant toute la conduite, même à l\'arrêt provisoire au feu rouge.', difficulty: 'easy' },
  { id: 'q8_4', module_id: 'm8', question_text: 'L\'alcool au volant entraîne principalement :', option_a: 'Une meilleure concentration', option_b: 'Un allongement du temps de réaction et une réduction du champ visuel', option_c: 'Une amélioration des réflexes', option_d: 'Aucun effet en dessous de 2 verres', correct_option: 'b', explanation: 'L\'alcool allonge le temps de réaction, réduit le champ visuel et crée un sentiment de fausse confiance. Même un verre peut altérer les réflexes.', difficulty: 'medium' },
  { id: 'q8_5', module_id: 'm8', question_text: 'En cas de contrôle de police, que devez-vous faire si vous contestez une infraction ?', option_a: 'Refuser de présenter vos documents', option_b: 'Discuter fermement sur place pour faire valoir vos droits', option_c: 'Présenter calmement vos documents et utiliser les recours légaux', option_d: 'Partir rapidement', correct_option: 'c', explanation: 'En cas de contrôle, présentez calmement vos documents. Ne discutez pas d\'une infraction sur place — les recours légaux existent pour contester.', difficulty: 'medium' },

  // Extra cross-module questions for variety
  { id: 'qx_1', module_id: 'm1', question_text: 'Un panneau "STOP" vous impose :', option_a: 'De ralentir fortement', option_b: 'De vous arrêter complètement, puis de céder le passage', option_c: 'De céder le passage sans vous arrêter', option_d: 'De klaxonner avant de passer', correct_option: 'b', explanation: 'Le panneau STOP impose un arrêt total (vitesse = 0) avant de s\'engager. Vous devez ensuite céder le passage à tous les véhicules.', difficulty: 'easy' },
  { id: 'qx_2', module_id: 'm2', question_text: 'Le panneau "Cédez le passage" (triangle pointe en bas) oblige à :', option_a: 'S\'arrêter comme au STOP', option_b: 'Ralentir et céder le passage sans nécessairement s\'arrêter', option_c: 'Klaxonner', option_d: 'Accélérer pour dégager la voie', correct_option: 'b', explanation: 'Le "Cédez le passage" oblige à ralentir et à laisser passer les autres usagers, mais ne nécessite pas d\'arrêt complet si la voie est libre.', difficulty: 'easy' },
  { id: 'qx_3', module_id: 'm4', question_text: 'La distance de freinage d\'un véhicule à 90 km/h est environ :', option_a: '20 mètres', option_b: '45 mètres', option_c: '70 mètres', option_d: '100 mètres', correct_option: 'b', explanation: 'À 90 km/h, la distance de freinage est d\'environ 45 mètres (sur route sèche). La distance totale d\'arrêt (réaction + freinage) est d\'environ 80 mètres.', difficulty: 'hard' },
  { id: 'qx_4', module_id: 'm3', question_text: 'En zone 30, la vitesse maximale est de :', option_a: '20 km/h', option_b: '30 km/h', option_c: '40 km/h', option_d: '50 km/h', correct_option: 'b', explanation: 'En zone 30 (signalée par un panneau rond blanc avec "30"), la vitesse maximale est de 30 km/h. Ces zones se trouvent souvent près des écoles.', difficulty: 'easy' },
  { id: 'qx_5', module_id: 'm5', question_text: 'À quel endroit ne peut-on jamais s\'arrêter ?', option_a: 'Sur une place de parking', option_b: 'Sur un passage piéton', option_c: 'Devant un garage non utilisé', option_d: 'Sur le côté droit d\'une route peu fréquentée', correct_option: 'b', explanation: 'S\'arrêter sur un passage piéton est strictement interdit car cela met en danger les piétons et obstrue le passage.', difficulty: 'easy' },
]

export const FAKE_LEADERBOARD = [
  { id: 'fake1', name: 'Koffi A.', coins_balance: 485, streak_count: 12 },
  { id: 'fake2', name: 'Ama B.', coins_balance: 420, streak_count: 8 },
  { id: 'fake3', name: 'Yao M.', coins_balance: 375, streak_count: 15 },
]
